apiVersion: secret.jenkins-x.io/v1alpha1
kind: Schema
spec:
  objects:
    - name: github-sdlc-app
      mandatory: false
      properties:
        - name: privateKey
          question: GitHubApp private key
        - name: installId
          question: GitHubApp installId
        - name: appId
          question: GitHubApp appId
    - name: slack
      mandatory: false
      properties:
        - name: token
          question: slack token
          help: slack auth token
        - name: defaultRecipient
          question: your default notification channel
    - name: snyk
      mandatory: false
      properties:
        - name: SNYK_TOKEN
          minLength: 5
          maxLength: 41
          generator: password
          question: snyk token
          help: snyk auth token
    - name: sonar
      mandatory: true
      properties:
        - name: sonar-login
          question: sonar token
          minLength: 5
          maxLength: 41
          generator: password
          help: Sonar auth token
        - name: sonar-host-url
          question: "sonar host url. like: https://sonarcloud.io"
          help: Sonar host
          defaultValue: https://sonarcloud.io
        - name: sonar-scm-provider
          question: "sonar host url. like: git"
          help: Sonar scm provider
          defaultValue: git
        - name: sonar-organization
          question: "sonar organization name. like vitech"
          help: 'sonar organization name. see: https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/'
          minLength: 5
          maxLength: 41
          generator: password
