filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: monitoring
repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: vitech-sdlc
  url: https://vitech-team-sdlc.github.io/sdlc-charts
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
releases:
- chart: prometheus-community/kube-prometheus-stack
  version: 16.12.2
  name: monitoring
  values:
  - jx-values.yaml
  - ../../versionStream/charts/prometheus-community/kube-prometheus-stack/values.yaml
  - ../../versionStream/charts/prometheus-community/kube-prometheus-stack/values.yaml.gotmpl
- chart: vitech-sdlc/monitoring
  version: 0.3.0
  name: prometheus-monitors
  values:
  - jx-values.yaml
  - ../../versionStream/charts/vitech-sdlc/monitoring/values.yaml
- chart: jxgh/grafana-dashboard
  version: 0.2.2
  name: grafana-dashboard
  values:
  - ../../versionStream/charts/jxgh/grafana-dashboard/values.yaml.gotmpl
  - jx-values.yaml
- chart: grafana/loki
  version: 2.5.0
  name: loki
  values:
  - ../../versionStream/charts/grafana/loki/values.yaml
  - jx-values.yaml
- chart: grafana/promtail
  version: 3.5.0
  name: promtail
  values:
  - ../../versionStream/charts/grafana/promtail/values.yaml
  - jx-values.yaml
- chart: grafana/tempo
  version: 0.6.8
  name: tempo
  values:
  - ../../versionStream/charts/grafana/tempo/values.yaml
  - jx-values.yaml
templates: {}
renderedvalues: {}
