environments:
  default:
    values:
    - jx-values.yaml
---
namespace: cert-manager
repositories:
- name: jetstack-oci
  url: quay.io/jetstack/charts
  oci: true
releases:
- chart: jetstack-oci/cert-manager
  version: v1.15.5
  condition: jxRequirementsIngressTLS.enabled
  name: cert-manager
  values:
  - ../../versionStream/charts/jetstack/cert-manager/values.yaml.gotmpl
  - jx-values.yaml
  - ../../versionStream/charts/jetstack-oci/cert-manager/values.yaml.gotmpl
