filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: cert-manager
repositories:
- name: jetstack
  url: https://charts.jetstack.io
releases:
- chart: jetstack/cert-manager
  version: 1.7.2
  condition: jxRequirementsIngressTLS.enabled
  name: cert-manager
  values:
  - ../../versionStream/charts/jetstack/cert-manager/values.yaml.gotmpl
  - jx-values.yaml
templates: {}
renderedvalues: {}
