filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: secret-infra
repositories:
- name: external-secrets
  url: https://external-secrets.github.io/kubernetes-external-secrets
- name: wave-k8s
  url: https://wave-k8s.github.io/wave/
releases:
- chart: external-secrets/kubernetes-external-secrets
  version: 8.5.5
  name: kubernetes-external-secrets
  values:
  - ../../versionStream/charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
  - jx-values.yaml
- chart: wave-k8s/wave
  version: 4.2.0
  name: wave
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
