apiVersion: gitops.jenkins-x.io/v1alpha1
kind: Schema
spec:
  objects:
    - name: monitoring-grafana
      mandatory: true
      properties:
        - name: admin-password
          minLength: 5
          maxLength: 41
          generator: password
          question: root password
          help: root passowrd for mysql
        - name: admin-user
          question: admin user name
          help: admin user name
          defaultValue: admin
        - name: ldap-toml
          question: ldap-toml
          help: ldap-toml
          defaultValue: ""
