filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx
repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: stable
  url: https://charts.helm.sh/stable
- name: vitech-sdlc
  url: https://vitech-team-sdlc.github.io/sdlc-charts
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
- name: k8s-at-home
  url: https://k8s-at-home.com/charts
releases:
- chart: bitnami/external-dns
  version: 5.0.0
  condition: jxRequirementsIngressExternalDNS.enabled
  name: external-dns
  values:
  - ../../versionStream/charts/bitnami/external-dns/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/jxboot-helmfile-resources
  version: 1.1.12
  name: jxboot-helmfile-resources
  values:
  - ../../versionStream/charts/jxgh/jxboot-helmfile-resources/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/jenkins-x-crds
  version: 3.0.11
  name: jenkins-x-crds
  values:
  - ../../versionStream/charts/jxgh/jenkins-x-crds/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/jx-pipelines-visualizer
  version: 1.7.5
  name: jx-pipelines-visualizer
  values:
  - ../../versionStream/charts/jxgh/jx-pipelines-visualizer/values.yaml.gotmpl
  - pv-values.yaml
  - jx-values.yaml
- chart: jxgh/jx-preview
  version: 0.0.192
  name: jx-preview
  values:
  - jx-values.yaml
- chart: jxgh/lighthouse
  version: 1.3.2
  name: lighthouse
  values:
  - ../../versionStream/charts/jxgh/lighthouse/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/nexus
  version: 0.1.41
  name: nexus
  values:
  - ../../versionStream/charts/jxgh/nexus/values.yaml.gotmpl
  - jx-values.yaml
- chart: stable/chartmuseum
  version: 2.14.2
  name: chartmuseum
  values:
  - ../../versionStream/charts/stable/chartmuseum/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/jx-build-controller
  version: 0.3.9
  name: jx-build-controller
  values:
  - ../../versionStream/charts/jxgh/jx-build-controller/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/acme
  version: 0.0.24
  condition: jxRequirementsIngressTLS.enabled
  name: acme-jx
  values:
  - ../../versionStream/charts/jxgh/acme-jx/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/jx-kh-check
  version: 0.0.78
  name: health-checks-jx
  values:
  - ../../versionStream/charts/jxgh/health-checks-jx/values.yaml.gotmpl
  - jx-values.yaml
- chart: vitech-sdlc/secret
  version: 0.1.0
  name: secret
  values:
  - jx-values.yaml
  - ../../versionStream/charts/vitech-sdlc/secret/values.yaml
- chart: vitech-sdlc/tektonpipelines
  version: 0.13.0
  name: tektonpipelines
  values:
  - jx-values.yaml
  - ../../versionStream/charts/vitech-sdlc/tektonpipelines/values.yaml.gotmpl
- chart: k8s-at-home/oauth2-proxy
  version: 5.0.3
  name: oauth2-proxy
  values:
  - ../../versionStream/charts/k8s-at-home/oauth2-proxy/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/cd-indicators
  version: 0.0.13
  name: cd-indicators
  values:
  - ../../versionStream/charts/jxgh/cd-indicators/values.yaml
  - jx-values.yaml
templates: {}
renderedvalues: {}
