ingress:
  annotations:
    nginx.ingress.kubernetes.io/auth-secret: ""
    nginx.ingress.kubernetes.io/auth-type: ""
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth