apiVersion: gitops.jenkins-x.io/v1alpha1
kind: Schema
spec:
  objects:
  - name: redis
    mandatory: true
    properties:
    - name: redis-password
      key: secret/data/redis
      question: redis password
      help: redis password
      minLength: 8
      maxLength: 16
      generator: password
