apiVersion: secret.jenkins-x.io/v1alpha1
kind: Schema
spec:
  objects:
  - name: grafana-slack-notifier
    properties:
    - name: notifier.yml
      question: Alert Notification Channels Config
      help: |
        https://grafana.com/docs/grafana/latest/administration/provisioning/#alert-notification-channels
      noMask: true
      template: |-
        notifiers:
          - name: slack
            type: slack
            uid: notifier1
            is_default: true
            send_reminder: true
            frequency: 1h
            disable_resolve_message: false
            settings:
              recipient: '{{ extsecret "slack" "defaultRecipient" }}'
              uploadImage: true
            secure_settings:
              token: '{{ extsecret "slack" "token" }}'
